services:
  php:
    build: .
    container_name: docker-template-php
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
    networks:
      - docker-template-php
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
      PHP_IDE_CONFIG: "serverName=docker-template-php"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: docker-template-php-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - docker-template-php

  db:
    image: mysql:8.0
    container_name: docker-template-php-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker-template-php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: docker-template-php-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - docker-template-php

networks:
  docker-template-php:

volumes:
  db_data: